# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WXNOQEulfg6at2zMtRLftC2A_m5G0Zbi
"""

import pickle
import pandas as pd
import numpy as np
import pefile
import math

with open("pe_malware_model.pkl", "rb") as f:
    data = pickle.load(f)

model = data["model"]
scaler = data["scaler"]
columns = data["columns"]

def get_entropy(file_path):
    with open(file_path,"rb") as f:
        data = f.read()
    if len(data) == 0:
        return 0
    entropy = 0
    for x in range(256):
        p = data.count(x)/len(data)
        if p > 0:
            entropy -= p*math.log2(p)
    return entropy

def extract_file_feature(fileName, columns):
    pe = pefile.PE(fileName)
    feature_map = {
        "Image_Base": lambda pe: pe.OPTIONAL_HEADER.ImageBase,
        "Base_of_Code": lambda pe: pe.OPTIONAL_HEADER.BaseOfCode,
        "Address_of_Entry_Point": lambda pe: pe.OPTIONAL_HEADER.AddressOfEntryPoint,
        "Size_of_Image": lambda pe: pe.OPTIONAL_HEADER.SizeOfImage,
        "Size_of_Code": lambda pe: pe.OPTIONAL_HEADER.SizeOfCode,
        "Subsystem": lambda pe: pe.OPTIONAL_HEADER.Subsystem,
        "num_sections": lambda pe: len(pe.sections),
        "num_dlls": lambda pe: len(pe.DIRECTORY_ENTRY_IMPORT) if hasattr(pe,'DIRECTORY_ENTRY_IMPORT') else 0,
        "num_functions": lambda pe: sum(len(entry.imports) for entry in pe.DIRECTORY_ENTRY_IMPORT) if hasattr(pe,'DIRECTORY_ENTRY_IMPORT') else 0,
    }
    file_feature = {}
    for col in columns:
        try:
            file_feature[col] = feature_map[col](pe) if col in feature_map else 0
        except:
            file_feature[col] = 0
    pe.close()
    file_feature["Entropy"] = get_entropy(fileName)
    return file_feature

def predict_file(feature, model, scaler, columns):
    feature = pd.DataFrame([feature])
    for col in ['Size_of_Image','Size_of_Code']:
        if col in feature.columns: feature[col] = np.log1p(feature[col])
    feature = feature[columns]
    feature_scaled = scaler.transform(feature)
    y_prob = model.predict_proba(feature_scaled)[:,1]
    y_pred = (y_prob>0.4).astype(int)
    return y_pred[0], y_prob[0]

# import sys
# sys.path.append("/home/user/malware_module")
# from mal import analyze_file -> 이거 하셔가지고
# 이 함수 사용하면 됩니당
def analyze_file(path):
    file_feature = extract_file_feature(sample_path, columns)
    pred, prob = predict_file(file_feature, model, scaler, columns)
    result_json = {
        "module": "File_Analyzer",
        "is_malicious": int(pred),
        "confidence_score": float(round(prob,4)),
        "detected_features": [
            f"Entropy={round(file_feature['Entropy'],4)}",
            f"Crypto_prob={round(prob,4)}"
        ]
    }
    return result_json

